"""Feature extractor benchmarking with MiniBatchKMeans-backed OverlapIndex."""

__version__ = "0.1.0"

from vertebrae.benchmark import Benchmark
from vertebrae.cache import (
    ArtifactStoreConfig,
    GCSArtifactStore,
    LocalArtifactStore,
    S3ArtifactStore,
    create_artifact_store,
)
from vertebrae.compression import compress_embedding_artifact_key, compress_embeddings
from vertebrae.config import (
    CacheConfig,
    ContinuousOverlapScoringConfig,
    EmbeddingCompressionConfig,
    EmbeddingConfig,
    LabelViewConfig,
    MemoryConfig,
    OverlapScoringConfig,
    SegmentationConfig,
    SeparatixConfig,
    StabilityConfig,
    TargetViewConfig,
)
from vertebrae.datasets import (
    BenchmarkDataset,
    EmbeddingUnitDataset,
    SegmentationAnnotation,
    SegmentationDataset,
    TargetView,
)
from vertebrae.evaluator import Evaluator
from vertebrae.execution import (
    CompressionJob,
    DaskBackend,
    EmbeddingJob,
    EmbeddingMergeJob,
    EmbeddingShardJob,
    LocalBackend,
    RayBackend,
    ResourceSpec,
    SampleBatch,
    ScoringJob,
    SeparatixJob,
    ShardSpec,
    benchmark_result_from_artifacts,
    collect_score_artifacts,
    compress_embedding_artifact,
    create_execution_backend,
    diagnose_embedding_artifact,
    embedding_artifact_key,
    embedding_output_key,
    embedding_output_shard_key,
    embedding_shard_key,
    groups_artifact_key,
    labels_artifact_key,
    materialize_and_merge_embeddings,
    materialize_embedding_shard,
    materialize_embedding_shards,
    materialize_group_artifact,
    materialize_label_artifact,
    materialize_segmentation_artifacts,
    merge_embedding_shards,
    plan_compression_job,
    plan_embedding_shard_jobs,
    plan_scoring_jobs,
    score_embedding_artifact,
    score_embedding_artifacts,
    scoring_artifact_key,
    separatix_artifact_key,
    validate_embedding_label_artifacts,
)
from vertebrae.extractors.base import EmbeddingOutput, EmbeddingOutputSpec
from vertebrae.extractors.huggingface_multimodal import HFMultimodalExtractor
from vertebrae.extractors.spatial import (
    CallableSpatialExtractor,
    PrecomputedSpatialExtractor,
    SpatialEmbeddingOutput,
    SpatialLayout,
    SpatialOutputSpec,
)
from vertebrae.results import BenchmarkResult, ExtractorResult

__all__ = [
    "Benchmark",
    "BenchmarkDataset",
    "BenchmarkResult",
    "CacheConfig",
    "CompressionJob",
    "ContinuousOverlapScoringConfig",
    "DaskBackend",
    "diagnose_embedding_artifact",
    "EmbeddingUnitDataset",
    "EmbeddingOutput",
    "EmbeddingOutputSpec",
    "CallableSpatialExtractor",
    "PrecomputedSpatialExtractor",
    "SpatialEmbeddingOutput",
    "SpatialLayout",
    "SpatialOutputSpec",
    "EmbeddingCompressionConfig",
    "EmbeddingConfig",
    "EmbeddingJob",
    "EmbeddingMergeJob",
    "EmbeddingShardJob",
    "Evaluator",
    "ExtractorResult",
    "HFMultimodalExtractor",
    "GCSArtifactStore",
    "LocalArtifactStore",
    "LocalBackend",
    "LabelViewConfig",
    "MemoryConfig",
    "OverlapScoringConfig",
    "RayBackend",
    "S3ArtifactStore",
    "ResourceSpec",
    "SampleBatch",
    "ScoringJob",
    "SeparatixConfig",
    "SegmentationConfig",
    "SegmentationAnnotation",
    "SegmentationDataset",
    "SeparatixJob",
    "ShardSpec",
    "ArtifactStoreConfig",
    "benchmark_result_from_artifacts",
    "collect_score_artifacts",
    "compress_embedding_artifact",
    "StabilityConfig",
    "TargetView",
    "TargetViewConfig",
    "create_artifact_store",
    "compress_embedding_artifact_key",
    "compress_embeddings",
    "embedding_artifact_key",
    "embedding_output_key",
    "embedding_output_shard_key",
    "embedding_shard_key",
    "labels_artifact_key",
    "groups_artifact_key",
    "materialize_and_merge_embeddings",
    "materialize_embedding_shard",
    "materialize_embedding_shards",
    "materialize_label_artifact",
    "materialize_group_artifact",
    "materialize_segmentation_artifacts",
    "merge_embedding_shards",
    "plan_compression_job",
    "plan_embedding_shard_jobs",
    "plan_scoring_jobs",
    "score_embedding_artifact",
    "score_embedding_artifacts",
    "scoring_artifact_key",
    "separatix_artifact_key",
    "validate_embedding_label_artifacts",
    "create_execution_backend",
]
